#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm *.log

cleanCase0

rm -rf VTK
rm -rf constant/cellToRegion
rm -rf constant/*/polyMesh  # region meshes
#------------------------------------------------------------------------------
